"""initial_schema

Revision ID: d5e15a37d6eb
Revises: 
Create Date: 2026-06-27 16:44:26.078864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e15a37d6eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACCEPTING_UPLOADS', 'PROCESSING', 'GRADED', 'EXPORTED', name='exam_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=True)

    op.create_table('answer_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'DECOMPOSING', 'EMBEDDING', 'READY', 'FAILED', name='answer_key_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('answer_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_roll', sa.String(length=50), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PREPROCESSING', 'OCR_RUNNING', 'OCR_DONE', 'EVALUATING', 'EVALUATED', 'FAILED', name='sheet_status'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_sheets', schema=None) as batch_op:
        batch_op.create_index('ix_answer_sheets_exam_id', ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_sheets_student_roll'), ['student_roll'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('rubric_hints', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'question_number', name='uq_exam_question_number')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_exam_id', ['exam_id'], unique=False)

    op.create_table('answer_key_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_key_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chroma_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['answer_key_id'], ['answer_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_key_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_akc_answer_key_id', ['answer_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_key_chunks_chroma_id'), ['chroma_id'], unique=False)

    op.create_table('extracted_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_sheet_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_answers', schema=None) as batch_op:
        batch_op.create_index('ix_extracted_answers_sheet_id', ['answer_sheet_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_sheet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING', name='job_status'), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_processing_jobs_sheet_id', ['answer_sheet_id'], unique=False)

    op.create_table('sheet_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_sheet_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('ocr_raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sheet_pages', schema=None) as batch_op:
        batch_op.create_index('ix_sheet_pages_answer_sheet_id', ['answer_sheet_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extracted_answer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('concept_scores', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_band'), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'AUTO_APPROVED', 'NEEDS_REVIEW', 'REVIEWED', 'OVERRIDDEN', 'SKIPPED', name='review_status'), nullable=False),
    sa.Column('answer_key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_answer_id'], ['extracted_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extracted_answer_id')
    )
    op.create_table('confidence_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_result_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confidence_flags', schema=None) as batch_op:
        batch_op.create_index('ix_confidence_flags_eval_id', ['evaluation_result_id'], unique=False)

    op.create_table('teacher_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_result_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=100), nullable=False),
    sa.Column('old_score', sa.Float(), nullable=False),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_overrides', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_overrides_eval_id', ['evaluation_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_overrides', schema=None) as batch_op:
        batch_op.drop_index('ix_teacher_overrides_eval_id')

    op.drop_table('teacher_overrides')
    with op.batch_alter_table('confidence_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_confidence_flags_eval_id')

    op.drop_table('confidence_flags')
    op.drop_table('evaluation_results')
    with op.batch_alter_table('sheet_pages', schema=None) as batch_op:
        batch_op.drop_index('ix_sheet_pages_answer_sheet_id')

    op.drop_table('sheet_pages')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_processing_jobs_sheet_id')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('extracted_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_extracted_answers_sheet_id')

    op.drop_table('extracted_answers')
    with op.batch_alter_table('answer_key_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_key_chunks_chroma_id'))
        batch_op.drop_index('ix_akc_answer_key_id')

    op.drop_table('answer_key_chunks')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_exam_id')

    op.drop_table('questions')
    with op.batch_alter_table('answer_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_sheets_student_roll'))
        batch_op.drop_index('ix_answer_sheets_exam_id')

    op.drop_table('answer_sheets')
    op.drop_table('answer_keys')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))

    op.drop_table('students')
    op.drop_table('exams')
    # ### end Alembic commands ###
